services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: luyen-thi-client
    ports:
      - "${PORT}:${PORT}"
    environment:
      - NODE_ENV=${NODE_ENV}
      - API_URL=${NEXT_PUBLIC_BASE_URL}
    networks:
      - npm_network

networks:
  npm_network:
    external: true
