export const API_PATH = {
  LOGIN: "/auth/login",
  REGISTER: "/auth/register",
  PROFILE: "/user/general",
  LOGOUT: "/logout",
  PACKAGE: "/vip-packages",
  ORDERS: "/orders",
  EXAMS: "/exams",
  EXAM_SCHEDULES: "/exam-schedules",
  BLOG_POSTS: "/blogposts",
  TAKE_EXAM: "/take-exam",
  GRADING_REQUEST: "/grading-request",
  PAYMENT: "/payment",
  SETTINGS: "/settings",
  ADMIN_USERS: "/admin/users",
  ADMIN_CREATE_USER: "/admin/create/user",
  ADMIN_UPDATE_USER: "/admin/update/user",
  ADMIN_DELETE_USER: "/admin/delete/user",
};
