export const API_PATH = {
  LOGIN: "/auth/login",
  REGISTER: "/auth/register",
  PROFILE: "/user/general",
  LOGOUT: "/logout",
  PACKAGE: "/vip-packages",
  ORDERS: "/orders",
  EXAMS: "/exams",
  EXAMS_LIST_BY_TYPE: "/exams/listExamByType",
  EXAM_SCHEDULES: "/exam-schedules",
  EXAM_SCHEDULES_RECENT: "/exam-schedules/recent",
  EXAM_SCHEDULES_FILTER: "/exam-schedules/filter",
  BLOG_POSTS: "/blogposts",
  TAKE_EXAM: "/take-exam",
  GRADING_REQUEST: "/grading-request",
  PAYMENT: "/payment",
  SETTINGS: "/settings",
  ADMIN_USERS: "/admin/users",
  ADMIN_CREATE_USER: "/admin/create/user",
  ADMIN_UPDATE_USER: "/admin/update/user",
  ADMIN_DELETE_USER: "/admin/delete/user",
  LECTURER_USER_RESPONSES: "/lecturer/user-responses",
  LECTURER_GRADE: "/lecturer/grade",
  UPLOAD_FILE: "/audio/upload",
  DOWNLOAD_FILE: "/audio/",
  HISTORY: "/history",
};
